[build]
publish = "/"

# https://docs.netlify.com/configure-builds/file-based-configuration/#post-processing
# If skip_processing = true, all other settings are ignored
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[redirects]]
  from = "https://chrisshortme.netlify.app/*"
  to = "https://chrisshort.me/:splat"
  status = 301
  force = true

  [[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = 'fullscreen=(self "https://chrisshort.me"), geolocation=(), camera=(), microphone=()'
